services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:
      - MONGO_URL=mongodb://db:27017/assignment
      - APP_PORT=3000  # Change the port to 3000
    ports:
      - '3000:3000'  # Update the port mapping

  db:
    container_name: db
    image: mongo:4.0
    restart: always
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3030:3030'  # Change the port mapping
    environment:
      - BACKEND_URL=http://localhost:3000  # Update the backend URL
