services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    environment:
      - FRONTEND_URL=http://localhost:3030
      - MONGO_URL=mongodb://db:27017/assignment
      - APP_PORT=3000  # Change the port to 3000
      - JWT_TOKEN=024f5966a0596e76a9c9a57b2b3deac1d3b587fd3d6483c080bbcf0e0e2041a1
      - GMAIL_ADDRESS=ggbarassignmentcreation@gmail.com
      - GMAIL_APP_PASSWORD=kqnt qpmh tfpr jrbt
      - GMAIL_PASSWORD=Dyq?=%Fm}0G&=;f-9?*mi%ShY6qjB#W(
      - EMBEDDED_USER=cf1fd5d6e2dbbc765e3b128bda187d26
    ports:
      - '3000:3000'  # Update the port mapping

  db:
    container_name: db
    image: mongo:4.0
    restart: always

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3030:3030'  # Change the port mapping
    environment:
      - BACKEND_URL=http://localhost:3000
